[project]
name = "llm_discord_bot"
dynamic = ["version"]
authors = [ { name="Joshua von Damm", email="jvondamm@gmail.com" } ]
description = "Discord chatbot that utilizes a local LLM for processing with a learning RAG pipeline"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "operating System :: OS Independent",
]

dependencies = [
    "discord >= 2.3.2",
    "dotenv >= 0.9.9",
    "torch >= 2.6.0",
    "transformers >= 4.51.3",
    "accelerate >= 1.6.0",
    "datasets >= 3.5.1",
    "sentence-transformers >= 2.2.2",
    "faiss-cpu >= 1.7.4",
    "langchain-community >= 0.3.23",
    "langchain-huggingface >= 0.1.2",
    "bitsandbytes >= 0.45.5",
    "table2ascii == 1.1.3",
    "faiss-cpu >= 1.11.0"
]

[project.optional-dependencies]
dev = [
    "pre-commit >= 4.2.0",
    "ruff >= 0.11.6",
    "uv >= 0.6.16"
]

[project.scripts]
bot = "llm_dicsord_bot.__main__:main"

[tool.ruff]
line-length = 120
exclude = [
    "bot.env",
    "config.json"
]

log_format = "%(asctime)s.%(msecs)%03d %(levelname)-8s %(name)-15s [%(filename)s:%(lineno)d] %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"

# pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128